### ISSUE TITLE
Any plans on macOS support?

### ISSUE THREAD

**Issue by agustif** [CyanSalt/todu#10] opened 2017-12-27 17:54 UTC
Wanted to try the app but didn't find a dmg file in the releases, is there some reason for it being only win/linux?

**Comment by CyanSalt** [comment] 2018-01-05 10:38
It's not very difficult to compile this app to a macOS dmg. Anybody can just clone this repository and run `npm install && npm run build` to build it by itself. Errors caused by missing files can be resolved by copying those files from the zip of windows version.
I use Windows and it seems complicated to create symlinks for the macOS package. It will be much better if you can build it yourself.

**Comment by tylwright** [comment] 2018-02-18 02:47
#12 fixes the missing file error.  `npm install && npm run build` will yield a todu.app artifact.

**Closed as completed** 2022-02-13 01:16 UTC
